#docker-compose.yaml
version: '3.8'

services:
  #====mysql====
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart:  unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "20041211wzwaicjW."
      MYSQL_USER: root
      MYSQL_PASSWORD: "20041211wzwaicjW."
      MYSQL_DATABASE: net_chat
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chat-net
  #===reids====
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - chat-net

  #====聊天室服务端=====

  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      #数据库配置
      #链接mysql环境配置
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=20041211wzwaicjW.
      - MYSQL_DATABASE=net_chat
      #连接redis环境配置
      - REDIS_ADDR=redis:6379
    networks:
      - chat-net

  #====网络与持久化
networks:
  chat-net:
    driver: bridge
volumes:
  redis_data:
  mysql_data: